# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GooDish' do
  pod 'AFNetworking', '~> 2.6'
  pod 'SDWebImage', '~>3.8' 
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GooDish

  target 'GooDishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GooDishUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
